### PR TITLE
added license moved recipe into repo

### PR DESCRIPTION
**Pull request by doutriaux1**

### CODE REVIEW

**Comment by doutriaux1** [comment]
@muryanto1 @dnadeau4 ping.

**Comment by doutriaux1** [comment]
@dnadeau4 you don't we can stick in recipe. I'm planning on doing this in another PR where I switch to setuptools and noarch but I can do it in this one if you want.

**Comment by dnadeau4** [comment]
ok.  Do you know why this is failing?

**Comment by doutriaux1** [comment]
numpy 1.15 vs numpy 1.14. I will try to force 1.14 in test suite. But we should address this.

**Comment by doutriaux1** [comment]
@muryanto1 @dnadeau4 ok it is ready now.

**Pull request merged**
